apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    purpose: roboshop
    component: rabbitmq
    tier: db
data:
  RABBITMQ_DEFAULT_USER: "roboshop"
  RABBITMQ_DEFAULT_PASS: "roboshop123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    purpose: roboshop
    component: rabbitmq
    tier: db
  namespace: roboshop
spec:
  # Specify replicas to be created
  replicas: 1
  selector:
    matchLabels:
      purpose: roboshop
    component: rabbitmq
    tier: db
  template:
    # pod definition
    metadata:
      labels:
        purpose: roboshop
        component: rabbitmq
        tier: db
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3
          imagePullPolicy: Always
          readinessProbe: # check if application is ready to serve requests
            tcpSocket:
              port: 5672
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe: # check if application is alive or not.
            tcpSocket:
              port: 5672
            initialDelaySeconds: 20
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: rabbitmq

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    purpose: roboshop
    component: rabbitmq
    tier: db
  ports:
    - protocol: TCP
      port: 5672 #  servicePort
      targetPort: 5672 #  containerPort
